// <auto-generated />
namespace SchedulingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedforignkeystocapandapplicationmodles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedforignkeystocapandapplicationmodles));
        
        string IMigrationMetadata.Id
        {
            get { return "201710061618290_added forign keys to cap and application modles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
